### 멤버조회
GET localhost:8080/accounts

### 멤버조회
GET localhost:8080/accounts/1


### 멤버생성
POST localhost:8080/accounts
Content-Type: application/json
Accept-Language: en

{
  "id" : "1",
  "password": "1",
  "email": "123@123",
  "state": "JOIN"
}



### 멤버수정
PUT localhost:8080/accounts/1
Content-Type: application/json

{
  "password": "1",
  "email": "321@321",
  "state": "SLEEPER"
}