### 멤버조회
GET localhost:8080/me


### 멤버조회
GET localhost:8080/me
Accept: application/xml


### 멤버조회
GET localhost:8080/members

### 멤버조회
GET localhost:8080/members/baek

### 멤버조회
GET localhost:8080/members/man


### 멤버생성
POST localhost:8080/members
Content-Type: application/json
Accept-Language: en

{
  "id" : "111",
  "name" : "111",
  "age" : 50,
  "class" : "A",
  "role" : "member"

}

### 멤버삭제
DELETE localhost:8080/members/1


### 멤버수정
PUT localhost:8080/members/baek
Content-Type: application/json

{
  "id" : "baek",
  "name" : "111",
  "age" : 123,
  "class" : "A",
  "role" : "member"

}